In [5]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
customer = pd.read_csv("../data/raw/olist_customers_dataset.csv")
seller = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

In [8]:
seller[seller.duplicated(subset= None, keep = 'first')]

Empty DataFrame
Columns: [seller_id, seller_zip_code_prefix, seller_city, seller_state]
Index: []

In [9]:
customer_count = customer.customer_state.value_counts()
# use value_counts() to generate the counts and put into DataFrame
customer_count_df = pd.DataFrame(customer_count).reset_index()

# set up the name of column
customer_count_df.columns = ['customer_state', 'cust_state_fre']
customer_count_df

   customer_state  cust_state_fre
0              SP           41746
1              RJ           12852
2              MG           11635
3              RS            5466
4              PR            5045
5              SC            3637
6              BA            3380
7              DF            2140
8              ES            2033
9              GO            2020
10             PE            1652
11             CE            1336
12             PA             975
13             MT             907
14             MA             747
15             MS             715
16             PB             536
17             PI             495
18             RN             485
19             AL             413
20             SE             350
21             TO             280
22             RO             253
23             AM             148
24             AC              81
25             AP              68
26             RR              46

In [ ]:
seller_count = seller.seller_state.value_counts()
# use value_counts() to generate the counts and put into DataFrame
seller_count_df = pd.DataFrame(seller_count).reset_index()

# set up the name of column
seller_count_df.columns = ['seller_state', 'seller_state_fre']
seller_count_df

In [ ]:
seller_customer_count = pd.merge(customer_count_df,seller_count_df, how='outer', left_on='customer_state', right_on='seller_state')
seller_customer_count.drop('seller_state', axis=1, inplace=True)
seller_customer_count.rename(columns={'customer_state': 'state_brief'}, inplace=True)
seller_customer_count

In [ ]:
seller_customer_count.fillna(0.1, inplace=True)

In [ ]:
seller_customer_count

In [ ]:
# input the full name of state, as powerbi can't reganize some breif name of state
state_mapping = {
    'AC': 'Acre',
    'AL': 'Alagoas',
    'AP': 'Amapá',
    'AM': 'Amazonas',
    'BA': 'Bahia',
    'CE': 'Ceará',
    'DF': 'Distrito Federal',
    'ES': 'Espírito Santo',
    'GO': 'Goiás',
    'MA': 'Maranhão',
    'MT': 'Mato Grosso',
    'MS': 'Mato Grosso do Sul',
    'MG': 'Minas Gerais',
    'PA': 'Pará',
    'PB': 'Paraíba',
    'PR': 'Paraná',
    'PE': 'Pernambuco',
    'PI': 'Piauí',
    'RJ': 'Rio de Janeiro',
    'RN': 'Rio Grande do Norte',
    'RS': 'Rio Grande do Sul',
    'RO': 'Rondônia',
    'RR': 'Roraima',
    'SC': 'Santa Catarina',
    'SP': 'São Paulo',
    'SE': 'Sergipe',
    'TO': 'Tocantins'
}

seller_customer_count['state_full_name'] = seller_customer_count['state_brief'].map(state_mapping)

display(seller_customer_count)

In [ ]:
display(seller_customer_count)

In [ ]:
seller_customer_count['customer_seller_ratio'] = seller_customer_count.cust_state_fre / seller_customer_count.seller_state_fre
seller_customer_count['seller_customer_ratio'] = seller_customer_count.seller_state_fre / seller_customer_count.cust_state_fre

In [ ]:
seller_customer_count['customer_seller_ratio'] = seller_customer_count['customer_seller_ratio'].round(3)
seller_customer_count['seller_customer_ratio'] = seller_customer_count['seller_customer_ratio'].round(3)
seller_customer_count

,state_brief,cust_state_fre,sell_state_fre,state_full_name,cust_sell_ratio,sell_cust_ratio
0,SP,41746,1849.0,São Paulo,22.578,0.044
1,RJ,12852,171.0,Rio de Janeiro,75.158,0.013
2,MG,11635,244.0,Minas Gerais,47.684,0.021
3,RS,5466,129.0,Rio Grande do Sul,42.372,0.024
4,PR,5045,349.0,Paraná,14.456,0.069
5,SC,3637,190.0,Santa Catarina,19.142,0.052
6,BA,3380,19.0,Bahia,177.895,0.006
7,DF,2140,30.0,Distrito Federal,71.333,0.014
8,ES,2033,23.0,Espírito Santo,88.391,0.011
9,GO,2020,40.0,Goiás,50.500,0.020
10,PE,1652,9.0,Pernambuco,183.556,0.005
11,CE,1336,13.0,Ceará,102.769,0.010
12,PA,975,1.0,Pará,975.000,0.001
13,MT,907,4.0,Mato Grosso,226.750,0.004
14,MA,747,1.0,Maranhão,747.000,0.001
15,MS,715,5.0,Mato Grosso do Sul,143.000,0.007
16,PB,536,6.0,Paraíba,89.333,0.011
17,PI,495,1.0,Piauí,495.000,0.002
18,RN,485,5.0,Rio Grande do Norte,97.000,0.010
19,AL,413,0.1,Alagoas,4130.000,0.000
20,SE,350,2.0,Sergipe,175.000,0.006
21,TO,280,0.1,Tocantins,2800.000,0.000
22,RO,253,2.0,Rondônia,126.500,0.008
23,AM,148,1.0,Amazonas,148.000,0.007
24,AC,81,1.0,Acre,81.000,0.012
25,AP,68,0.1,Amapá,680.000,0.001
26,RR,46,0.1,Roraima,460.000,0.002

In [ ]:
# export file
seller_customer_count.to_csv('../data/processed/customer_seller_ratio.csv', index=False)

In [ ]:
seller_customer_count.sort_values('customer_seller_ratio')

,state_brief,cust_state_fre,sell_state_fre,state_full_name,cust_sell_ratio,sell_cust_ratio
4,PR,5045,349.0,Paraná,14.456,0.069
5,SC,3637,190.0,Santa Catarina,19.142,0.052
0,SP,41746,1849.0,São Paulo,22.578,0.044
3,RS,5466,129.0,Rio Grande do Sul,42.372,0.024
2,MG,11635,244.0,Minas Gerais,47.684,0.021
9,GO,2020,40.0,Goiás,50.500,0.020
7,DF,2140,30.0,Distrito Federal,71.333,0.014
1,RJ,12852,171.0,Rio de Janeiro,75.158,0.013
24,AC,81,1.0,Acre,81.000,0.012
8,ES,2033,23.0,Espírito Santo,88.391,0.011
16,PB,536,6.0,Paraíba,89.333,0.011
18,RN,485,5.0,Rio Grande do Norte,97.000,0.010
11,CE,1336,13.0,Ceará,102.769,0.010
22,RO,253,2.0,Rondônia,126.500,0.008
15,MS,715,5.0,Mato Grosso do Sul,143.000,0.007
23,AM,148,1.0,Amazonas,148.000,0.007
20,SE,350,2.0,Sergipe,175.000,0.006
6,BA,3380,19.0,Bahia,177.895,0.006
10,PE,1652,9.0,Pernambuco,183.556,0.005
13,MT,907,4.0,Mato Grosso,226.750,0.004
26,RR,46,0.1,Roraima,460.000,0.002
17,PI,495,1.0,Piauí,495.000,0.002
25,AP,68,0.1,Amapá,680.000,0.001
14,MA,747,1.0,Maranhão,747.000,0.001
12,PA,975,1.0,Pará,975.000,0.001
21,TO,280,0.1,Tocantins,2800.000,0.000
19,AL,413,0.1,Alagoas,4130.000,0.000